### ISSUE TITLE
Config to prevent items from droppping in bazaar and near 3D printers

### ISSUE THREAD

**Issue by warallnight** [ThinkInvis/RoR2-Yeet#9]
### Is your feature request related to a problem? Please describe.
It is very profitable to throw the necessary items on the floor, giving unnecessary items to the printer or exchanger.

### Describe the solution you'd like
Add config for preventing items dropping in bazaar, and maybe in some configurable radius around 3D printers

**Comment by ThinkInvis** [comment]
Preventing mod functionality while in range of a type of interactable is kind of a slippery slope. A sufficiently motivated player wouldn't hesitate to run in/out of range of the object in question, using mobility skills or similar to make the process faster -- not to mention that they only need to do so _once_, dropping all their important items in one big batch before moving towards the printer. Even in the case of dropping single items at a time, a no-drop range large enough to prevent this could make finding spots to drop items in for other purposes difficult; covering the batch case would make it nigh-impossible.

3d796b12e5e5e1ca4af48ce266ebed215165e4b9: I've implemented this as a cooldown on dropping items instead. This will add a very large time cost (and thus extra progress on the difficulty meter) to cheating item exchanges in the manner described, due to the high number of item drops involved. The intended purpose of this mod -- allowing an undo for accidental pickups, as well as tweaks of a team's item distribution -- is less affected, and even balanced in the latter case (which could also be seen as too powerful to be able to do all at once).
